/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "MyVoiceAgent";
  }
  interface Env {
    AI: Ai;
    PLIVO_AUTH_ID: string;
    PLIVO_AUTH_TOKEN: string;
    PLIVO_PHONE_NUMBER: string;
    PLIVO_ENDPOINT_USERNAME: string;
    MyVoiceAgent: DurableObjectNamespace<import("./src/index").MyVoiceAgent>;
  }
}
interface Env extends Cloudflare.Env {}
